# docker-compose.yml (root)
x-app: &app
    build:
        context: .
        dockerfile: .devcontainer/Dockerfile
    user: "node"
    working_dir: /workspace
    environment:
        CI: "1"

services:
    cli:
        <<: *app
        profiles: ["dev"] # only shows up when you want it (docker compose --profile dev ...)
        command: bash # interactive shell

    ci:
        <<: *app
        profiles: ["ci"]
        environment:
            CI: "1"
            SKIP_ELECTRON_REBUILD: "1"
        command: >
            bash -lc "set -euxo pipefail &&
            pnpm -v &&
            pnpm install --frozen-lockfile &&
            pnpm -r run --if-present lint &&
            pnpm --filter ./apps/frontend run build:js &&
            pnpm --filter ./apps/frontend exec tailwindcss
              -i ./apps/frontend/renderer/input.css
              -o ./apps/frontend/renderer/tailwind.css &&
            node apps/frontend/electron/backend/db/migrate.js || true &&
            pnpm -r run --if-present test"

volumes:
    pnpm-store:
    node_modules_root:
    node_modules_frontend:
