services:
    cli:
        volumes:
            - .:/workspace
            - pnpm-store:/home/node/.local/share/pnpm
            - node_modules_root:/workspace/node_modules
            - node_modules_frontend:/workspace/apps/frontend/node_modules

    ci:
        volumes:
            - .:/workspace
            - pnpm-store:/home/node/.local/share/pnpm
            - node_modules_root:/workspace/node_modules
            - node_modules_frontend:/workspace/apps/frontend/node_modules

# use the same named volumes as root so they merge
volumes:
    pnpm-store:
    node_modules_root:
    node_modules_frontend:
