name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20" # no cache here

            - name: Enable pnpm via corepack
              run: |
                  corepack enable
                  corepack prepare pnpm@latest --activate
                  pnpm -v

            - name: Get pnpm store path
              id: pnpm-store
              run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            - name: Cache pnpm store
              uses: actions/cache@v4
              with:
                  path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
                  key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: pnpm-store-${{ runner.os }}-

            - name: Hard clean
              run: |
                  rm -rf node_modules
                  rm -rf ~/.cache/node-gyp ~/.npm/_npx ~/.electron-gyp

            - name: Install (allow postinstall)
              run: pnpm install --frozen-lockfile

            - name: Debug versions
              run: |
                  node -v
                  pnpm -v
                  node -e "console.log('electron devDep:', require('./apps/frontend/package.json').devDependencies?.electron)"
                  node -e "console.log('better-sqlite3 dep:', require('./apps/frontend/package.json').dependencies?.['better-sqlite3'] || require('./apps/frontend/package.json').devDependencies?.['better-sqlite3'])"
                  node -e "try{console.log('better-sqlite3 resolved:', require('./apps/frontend/node_modules/better-sqlite3/package.json').version)}catch(e){console.log('better-sqlite3 not found in app folder')}"
                  pnpm why better-sqlite3 || true

            - name: Rebuild native modules for Electron
              working-directory: apps/frontend
              run: pnpm dlx @electron/rebuild -v 38.0.0 -f -w better-sqlite3

            - name: Lint
              run: pnpm -r run --if-present lint

            - name: Build (renderer only)
              run: pnpm --filter ./apps/frontend run build:js

            - name: CSS build (non-watch)
              run: pnpm --filter ./apps/frontend exec tailwindcss -i ./renderer/input.css -o ./renderer/tailwind.css

            - name: Smoke check migrations (Node only)
              run: node apps/frontend/electron/backend/db/migrate.js || true

            - name: Tests
              run: pnpm -r run --if-present test
