name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20" # no cache here

            - name: Enable pnpm via corepack
              run: |
                  corepack enable
                  corepack prepare pnpm@latest --activate
                  pnpm -v

            # Cache the pnpm store (now that pnpm exists)
            - name: Get pnpm store path
              id: pnpm-store
              run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            - name: Cache pnpm store
              uses: actions/cache@v4
              with:
                  path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
                  key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      pnpm-store-${{ runner.os }}-

            - name: Install
              run: pnpm install --frozen-lockfile

            - name: Lint
              run: pnpm -r run lint --if-present

            - name: Build (renderer only)
              run: pnpm --filter ./apps/frontend run build:js

            - name: CSS build (non-watch)
              run: pnpm --filter ./apps/frontend exec tailwindcss -i ./apps/frontend/renderer/input.css -o ./apps/frontend/renderer/tailwind.css --watch=never

            - name: Smoke check migrations (Node only)
              run: node apps/frontend/electron/backend/db/migrate.js || true

            - name: Tests
              run: pnpm -r run test --if-present
