name: Release Windows

on:
    push:
        branches: [production]

env:
    NODE_VERSION: "20"
    ELECTRON_VERSION: "38.0.0" # <-- keep in sync with your app

permissions:
    contents: write

jobs:
    prepare:
        uses: ./.github/workflows/release-prepare.yml

    build-windows:
        needs: prepare
        runs-on: windows-latest
        environment: windows-release
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Enable pnpm via corepack
              shell: bash
              run: |
                  corepack enable
                  corepack prepare pnpm@latest --activate
                  pnpm -v

            - name: Setup Python 3.11 (for node-gyp)
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Point node-gyp at Python
              shell: bash
              run: echo "npm_config_python=$(python -c 'import sys; print(sys.executable)')" >> $GITHUB_ENV

            - name: Cache pnpm store
              id: pnpm-store
              shell: bash
              run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v4
              with:
                  path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
                  key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: pnpm-store-${{ runner.os }}-

            - name: Clean previous Electron headers/cache
              shell: bash
              run: |
                  rm -rf ~/.electron-gyp
                  rm -rf node_modules/.cache

            - name: Install deps
              shell: bash
              run: pnpm install --frozen-lockfile

            # ⬇️ Build renderer (Vite) so renderer/dist exists
            - name: Build renderer (Vite)
              working-directory: apps/frontend
              shell: bash
              run: pnpm run build

            # ⬇️ Rebuild native modules against Electron ABI
            - name: Rebuild native modules for Electron
              working-directory: apps/frontend
              shell: bash
              run: pnpm dlx @electron/rebuild -v ${{ env.ELECTRON_VERSION }} -f -w better-sqlite3

            # (Optional) Code signing would go here

            # ⬇️ Build Windows installer(s)
            - name: Build Windows artifacts (NSIS/MSI)
              working-directory: apps/frontend
              shell: bash
              run: pnpm run build:win

            # ⬇️ Upload correct output folder (matches electron-builder.yml: directories.output)
            - name: Upload to release (EXE/MSI)
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ needs.prepare.outputs.tag }}
                  files: |
                      apps/frontend/dist/release/*.exe
                      apps/frontend/dist/release/*.msi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
