name: Release Windows

on:
    push:
        branches: [production]

env:
    NODE_VERSION: "20"

permissions:
    contents: write

jobs:
    prepare:
        uses: ./.github/workflows/release-prepare.yml

    build-windows:
        needs: prepare
        runs-on: windows-latest
        environment: windows-release
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Enable pnpm via corepack
              shell: bash
              run: |
                  corepack enable
                  corepack prepare pnpm@latest --activate
                  pnpm -v

            - name: Setup Python 3.11
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Point node-gyp at Python
              shell: bash
              run: echo "npm_config_python=$(python -c 'import sys; print(sys.executable)')" >> $GITHUB_ENV

            - name: Get pnpm store path
              id: pnpm-store
              shell: bash
              run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            - name: Cache pnpm store
              uses: actions/cache@v4
              with:
                  path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
                  key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      pnpm-store-${{ runner.os }}-

            - name: Install deps
              shell: bash
              run: pnpm install --frozen-lockfile

            - name: Rebuild native modules for Electron
              working-directory: apps/frontend
              shell: bash
              run: pnpm exec electron-rebuild -f -w better-sqlite3

            - name: Setup signing (optional)
              shell: bash
              env:
                  WIN_CERT_B64: ${{ secrets.WIN_CERT_B64 || '' }}
                  WIN_CERT_PASSWORD: ${{ secrets.WIN_CERT_PASSWORD || '' }}
              run: |
                  if [ -n "$WIN_CERT_B64" ] && [ -n "$WIN_CERT_PASSWORD" ]; then
                    echo "$WIN_CERT_B64" | base64 --decode > win-codesign.pfx
                    echo "CSC_LINK=$(pwd)/win-codesign.pfx" >> $GITHUB_ENV
                    echo "CSC_KEY_PASSWORD=$WIN_CERT_PASSWORD" >> $GITHUB_ENV
                    echo "Windows signing: enabled"
                  else
                    echo "Windows signing: secrets not present, building unsigned."
                  fi

            - name: Build Windows artifacts (NSIS/MSI)
              working-directory: apps/frontend
              shell: bash
              run: pnpm run build:win

            - name: Upload to release (EXE/MSI)
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ needs.prepare.outputs.tag }}
                  files: |
                      apps/frontend/release/*.exe
                      apps/frontend/release/*.msi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
