name: Release Windows

on:
    push:
        branches: [production]

env:
    NODE_VERSION: "20"

permissions:
    contents: write

jobs:
    prepare:
        uses: ./.github/workflows/release-prepare.yml

    build-windows:
        needs: prepare
        runs-on: windows-latest
        environment: windows-release
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }} # no pnpm cache here

            # Enable pnpm via corepack
            - name: Enable pnpm via corepack
              shell: bash
              run: |
                  corepack enable
                  corepack prepare pnpm@latest --activate
                  pnpm -v

            # Python 3.11 for node-gyp (more reliable than 3.12+)
            - name: Setup Python 3.11
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Point node-gyp at Python 3.11
              shell: bash
              run: echo "npm_config_python=$(python -c 'import sys; print(sys.executable)')" >> $GITHUB_ENV

            # Cache pnpm store (after pnpm exists)
            - name: Get pnpm store path
              id: pnpm-store
              shell: bash
              run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            - name: Cache pnpm store
              uses: actions/cache@v4
              with:
                  path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
                  key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      pnpm-store-${{ runner.os }}-

            - name: Install deps
              shell: bash
              run: pnpm install --frozen-lockfile

            # Optional: Windows code signing
            - name: Setup signing (optional)
              if: ${{ secrets.WIN_CERT_B64 != '' }}
              shell: bash
              run: |
                  echo "$WIN_CERT_B64" | base64 --decode > win-codesign.pfx
                  echo "CSC_LINK=$(pwd)/win-codesign.pfx" >> $GITHUB_ENV
                  echo "CSC_KEY_PASSWORD=${WIN_CERT_PASSWORD}" >> $GITHUB_ENV
              env:
                  WIN_CERT_B64: ${{ secrets.WIN_CERT_B64 }}
                  WIN_CERT_PASSWORD: ${{ secrets.WIN_CERT_PASSWORD }}

            - name: Build Windows artifacts (NSIS/MSI)
              working-directory: apps/frontend
              shell: bash
              run: pnpm run build:win

            - name: Upload to release (EXE/MSI)
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ needs.prepare.outputs.tag }}
                  files: |
                      apps/frontend/release/*.exe
                      apps/frontend/release/*.msi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
